import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import classNames from 'classnames';
import '@/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className="h-full">
      <body className={classNames('h-full bg-neutral-900 text-white', inter.className)}>
        {children}
      </body>
    </html>
  );
}
